gen.M=250; %kg, total vehicle mass w/ driver
gen.Mf=114; %kg mass on front axle
gen.Mr=136; %mass on rear axle
gen.g=9.81; % gg
gen.h=0.325; % CG height
gen.mu=0.72; %tyre road friction coefficient
gen.v=12.5; % m/s cornering speed
gen.R=3; % m braking distance to a stop
gen.u=11.11; % m/s speed at brake application
gen.S=4.1; % m braking distance to a stop
gen.mWheel=5; % kg mass of one wheel assembly
gen.mUns=15; % kg mass of unsprung mass per corner
gen.kF=11.8; % N/mm front spring rate
gen.kR=14.8; % N/mm rear spring rate
gen.bump=30; % mm bump travel
gen.c=0.055; % m brake mount to rear upright centre
gen.dpin=22.5; % mm pinion pitch diameter
gen.accBrk=11.77; % m/s^2 braking deceleration
gen.accCor=13.73; % m/s^2 cornering acceleration