function [gen] = generalinputs()
    gen.M=250; %kg, total vehicle mass w/ driver
    gen.Mf=114; %kg mass on front axle
    gen.Mr=136; % kg mass on rear axle
    gen.g=9.81; % gg
    gen.h=325; % CG height (m)
    gen.mu=0.72; %tyre road friction coefficient
    gen.v=12.5; % m/s cornering speed
    gen.R=3; % m cornering radius
    gen.deacc=11.11; % m/s^2 braking deacc
    gen.S=4.1; % m braking distance to a stop
    gen.mWheel=5; % kg mass of one wheel assembly
    gen.mUns=15; % kg mass of unsprung mass per corner
    gen.kF=11.8; % N/mm front spring rate
    gen.kR=14.8; % N/mm rear spring rate
    gen.bump=30; % mm bump travel
    gen.c=55; % mm brake mount to rear upright centre
    gen.dpin=22.5; % mm pinion pitch diameter
    gen.accBrk=11.77; % m/s^2 braking deceleration
    gen.accCor=13.73; % m/s^2 cornering acceleration
    gen.loaded_radius=234.80; %mm
    gen.MR_F=1.429; %motion ratio front
    gen.MR_R=1.592; %motion ratio rear